#!/bin/bash

# run with sudo

apt install -y --no-install-recommends $(cat atom.list) || exit
apt install -y --no-install-recommends $(cat base.list)
apt install -y --no-install-recommends $(cat baseNoInstallRec.list)
#apt install -y $(cat extra.list)

# wbar
rm /etc/xdg/autostart/wbar.desktop # start wbar in ob autostart
